// <auto-generated />
using System;
using LoanCalcRD.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoanCalcRD.Infrastructure.Persistence.Migrations;

[DbContext(typeof(LoanCalcDbContext))]
partial class LoanCalcDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("LoanCalcRD.Domain.Loans.LoanSimulation", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<decimal>("Amount").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
            b.Property<decimal>("AnnualRate").HasPrecision(8, 4).HasColumnType("numeric(8,4)");
            b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<bool>("IsFavorite").HasColumnType("boolean");
            b.Property<string>("LoanType").IsRequired().HasMaxLength(30).HasColumnType("character varying(30)");
            b.Property<string>("Name").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
            b.Property<int>("TermMonths").HasColumnType("integer");
            b.Property<DateTimeOffset>("UpdatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<Guid>("UserId").HasColumnType("uuid");

            b.HasKey("Id");
            b.HasIndex("UserId", "CreatedAtUtc");
            b.HasIndex("UserId", "IsFavorite");
            b.ToTable("loan_simulations");
        });
#pragma warning restore 612, 618
    }
}
